[custom]
; 个人定制化 subconverter 配置文件 - 纯本地数据库极速版
; 尽可能使用本地 geosite、geoip 数据库

; 屏蔽广告与特定恶意网段
ruleset=🛑 屏蔽连接,[]GEOSITE,category-ads-all
ruleset=🛑 屏蔽连接,[]IP-CIDR,203.195.121.0/24

; 代理规则 (Google)
ruleset=✨ 代理,[]GEOSITE,google
ruleset=✨ 代理,[]GEOIP,google

; 直连规则 (CN)
ruleset=🎯 直连,[]GEOSITE,CN
ruleset=🎯 直连,[]GEOIP,CN,no-resolve

; 最终兜底：漏网之鱼流向节点选择
ruleset=🚀 节点选择,[]FINAL

custom_proxy_group=🚀 节点选择`select`[]PROXY`[]DIRECT`[]REJECT
custom_proxy_group=🛑 屏蔽连接`select`[]REJECT`[]DIRECT
custom_proxy_group=✨ 代理`select`[]🚀 节点选择`[]DIRECT
custom_proxy_group=🎯 直连`select`[]DIRECT`[]🚀 节点选择
; 开启规则生成
enable_rule_generator=true
overwrite_original_rules=true
